### ISSUE TITLE
Unable to build the HosseinDinarvand/FirstWeb.API.sln

### ISSUE THREAD

**Issue by VahidFarahmandian** [VahidFarahmandian/spoota-internship-roadmap#11]
**Describe the bug**
@HosseinDinarvand Our CI/CD tool is unable to automatically build your solution. 

Error: `HosseinDinarvand/SOLIDPrinciple/Program.cs(9,39): error CS7036: There is no argument given that corresponds to the required parameter '_employeeRepository' of 'EmployeeManager.EmployeeManager(IEmployeeRepository)'`

Detailed error message is available here: https://github.com/VahidFarahmandian/spoota-internship-roadmap/actions/runs/8313967476/job/22750552525

**To Reproduce**
1. Checkout the `main` branch
2. Build `HosseinDinarvand/FirstWeb.API.sln`

**Expected behavior**
Build will be failed with given error message

**Comment by HosseinDinarvand** [comment]
I fixed this bug and I send a pull request,
but i can't linked the pull request in this issuse.
I think the Development section are be closed for me.
